---

- selinux:
    state: disabled

- name: Install EPEL-Release
  yum:
    name: epel-release
    state: present

- name: Install some basic packages
  command: yum -y install python2-pip rsync wget net-tools open-vm-tools

- name: purge old docker packages
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
    - docker-engine

- name: install requirements
  yum:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - device-mapper-persistent-data
    - lvm2

- name: add docker-ce repository (centos7)
  yum_repository:
    name: docker-ce
    description: Docker Repository
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes
    file: docker

- name: install docker-ce
  yum:
    name: docker-ce
    update_cache: yes

#- name: set storage driver
#  blockinfile:
#    path: /etc/docker/daemon.json
#    create: yes
#    block: |
#      {
#        "storage-driver": "devicemapper"
#      }

- name: Make sure a service is running
  systemd: state=started name=docker

- name: enable service docker and ensure it is not masked
  systemd:
    name: docker
    enabled: yes
    masked: no

- name: Install docker-py
  pip: 
    name: docker-py

- name: Install docker-compose
  pip:
    name: docker-compose

