---
- name: Create stack dir
  file:
    path: /var/stacks/jenkins-stack
    state: directory
    mode: 0755

- name: Generate docker-compose file
  template:
    src=docker-compose.yml.j2
    dest=/var/stacks/jenkins-stack/docker-compose.yml

- name: Copy service file for jenkins-stack
  copy:
    src=jenkins-stack.service
    dest=/etc/systemd/system/jenkins-stack.service

- name: Restart jenkins
  systemd:
    state: started
    name: jenkins-stack
    enabled: yes
    daemon_reload: yes

