---
- name: Create stack dir
  file:
    path: /var/stacks/{{ stack_name }}-stack
    state: directory
    mode: 0755

- name: Generate docker-compose file
  template:
    src=docker-compose.yml.j2
    dest=/var/stacks/{{ stack_name }}-stack/docker-compose.yml

- name: Copy service file for stack
  template:
    src=../common/templates/stack.service.j2
    dest=/etc/systemd/system/{{ stack_name }}-stack.service

- name: Restart stack
  systemd:
    state: started
    name: "{{ stack_name }}-stack"
    enabled: yes
    daemon_reload: yes

- name: register jenkins service with the local consul agent
  consul:
    service_name: jenkins
    service_port: 8080

